comment_width = 120
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
reorder_impl_items = true
